#
# Makefile
#
# CS 50x
# Pset5
#

copy:
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -Wno-unused-variable -o copy copy.c -lm

resize:
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -Wno-unused-variable -o resize resize.c -lm

whodunit:
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -Wno-unused-variable -o whodunit whodunit.c -lm

samplepx:
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -Wno-unused-variable -o samplepx samplepx.c -lm

clean:
	rm -f *.o *copy.bmp onepx.bmp core copy whodunit resize samplepx
